class ErrorMessage:
    incorrect_phone_number = "incorrect phone number"
    invalid_email = "Invalid email"
    please_enter_phone_or_email = "enter your email or mobile phone number gg"
    user_is_not_registered = "user is not registered"
    there_was_a_problem = "there was a problem"
    invalid_email_format = "We cannot find an account with that email address"
    your_password_is_incorrect = "Your password is incorrect"
    enter_your_password = "Enter your password"
    review_your_address = "Review your address"
    invalid_coupon="Invalid coupon"